// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ENSEK_API.Models
{
    public partial class Accounts
    {
        public Accounts()
        {
            MeterReading = new HashSet<MeterReading>();
        }

        public int AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public virtual ICollection<MeterReading> MeterReading { get; set; }
    }
}