// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ENSEK_API.Models
{
    public partial class MeterReading
    {
        public int ReadingId { get; set; }
        public int AccountId { get; set; }
        public DateTime DateTime { get; set; }
        public int Value { get; set; }

        public virtual Accounts Account { get; set; }
    }
}